### ISSUE TITLE
Implement Stop Word Filter

### ISSUE THREAD

**Issue by ktallafus** [dachcom-digital/pimcore-dynamic-search-index-provider-lucene#1]

**Comment by solverat** [comment]
```yml

index_provider:
    service: 'lucene'
    options:
        database_name: 'ecommerce'
        analyzer:
            forced_locale: de
            stop_words:
                on_index_time: true
                on_query_time: false
                libraries:
                    -   locale: de
                        file: '%%dsl_stop_words_lib_path%%/de'
                    -   locale: fr
                        file: '%%dsl_stop_words_lib_path%%/fr'
                    -   locale: it
                        file: '%%dsl_stop_words_lib_path%%/it'
                    -   locale: en
                        file: '%%dsl_stop_words_lib_path%%/en'
```
