### ISSUE TITLE
Implement Stemming Filter

### ISSUE THREAD

**Issue by ktallafus** [dachcom-digital/pimcore-dynamic-search-index-provider-lucene#2]
Maybe use wamania/php-stemmer

**Comment by solverat** [comment]
```yml
index_provider:
    service: 'lucene'
    options:
        database_name: 'ecommerce'
        analyzer:
            forced_locale: de
            filter:
                -   on_index_time: true
                    on_query_time: true
                    locale_aware: true
                    class: '\DsLuceneBundle\Lucene\Analyzer\Stemming\SnowBallStemmingFilter'
```
